[package]
name = "mssim-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
nalgebra = "0.33"
js-sys = "0.3"

[dev-dependencies]
approx = "0.5"

[profile.release]
opt-level = "z"
lto = true
